// Code generated by MockGen. DO NOT EDIT.
// Source: ./infrastructure/persistent/user_repository.go
//
// Generated by this command:
//
//	mockgen -source ./infrastructure/persistent/user_repository.go -destination ./mock/infrastructure/persistent/user_repository_mock.go -package persistent_mock
//

// Package persistent_mock is a generated GoMock package.
package persistent_mock
