name: upsider-coding-test

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    tty: true
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: main
      DB_PASSWORD: main
      DB_NAME: main
    volumes:
      - .:/go/src/github.com/yt-d-rep/upsider-coding-test
  db:
    image: postgres:11
    environment:
      POSTGRES_DB: main
      POSTGRES_USER: main
      POSTGRES_PASSWORD: main
    ports:
      - "5436:5432"
    volumes:
      - ./data:/var/lib/postgresql/data