// Code generated by MockGen. DO NOT EDIT.
// Source: ./migration/migrate.go
//
// Generated by this command:
//
//	mockgen -source ./migration/migrate.go -destination ./mock/migration/migrate_mock.go -package ld ignore_mock
//

// Package ld is a generated GoMock package.
package ld
