// Code generated by MockGen. DO NOT EDIT.
// Source: ./infrastructure/handler/common.go
//
// Generated by this command:
//
//	mockgen -source ./infrastructure/handler/common.go -destination ./mock/infrastructure/handler/common_mock.go -package handler_mock
//

// Package handler_mock is a generated GoMock package.
package handler_mock
