@token={{login.response.body.$.token}}
@company_id=b8e7fce5-77a5-4e64-9e3c-90e0c5b4c17d
@partner_id=a5b6f8d4-9b44-4f9e-919f-d5cb2d7b8e9f

### POST /api/user
POST {{url:api}}/api/users
Content-Type: application/json

{
  "name": "John Doe",
  "email": "sample@sample.com",
  "password": "12345678",
  "company_id": "{{company_id}}"
}

### POST /api/login
# @name login
POST {{url:api}}/api/login
Content-Type: application/json

{
  "email": "sample@sample.com",
  "password": "12345678"
}

### POST /api/invoices
POST {{url:api}}/api/invoices
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "company_id": "{{company_id}}",
  "partner_id": "{{partner_id}}",
  "payment_amount": 10000
}

### GET /api/invoices
@from=2024-09-09T15%3A00%3A00Z
@to=2024-09-10T14%3A59%3A59Z
GET {{url:api}}/api/invoices?company_id={{company_id}}&from={{from}}&to={{to}}
Authorization: Bearer {{token}}
