// Code generated by MockGen. DO NOT EDIT.
// Source: ./infrastructure/middleware/interceptor.go
//
// Generated by this command:
//
//	mockgen -source ./infrastructure/middleware/interceptor.go -destination ./mock/infrastructure/middleware/interceptor_mock.go -package middleware_mock
//

// Package middleware_mock is a generated GoMock package.
package middleware_mock
