// Code generated by MockGen. DO NOT EDIT.
// Source: ./infrastructure/middleware/token.go
//
// Generated by this command:
//
//	mockgen -source ./infrastructure/middleware/token.go -destination ./mock/infrastructure/middleware/token_mock.go -package middleware_mock
//

// Package middleware_mock is a generated GoMock package.
package middleware_mock
